// Code generated by Slice Machine. DO NOT EDIT.

import Article from './Article';
import Body from './Body';
import Card from './Card';
import FullWidth from './FullWidth';
import NavigationItem from './NavigationItem';
import SectionGrid from './SectionGrid';
import TopGrid from './TopGrid';

export {
	Article,
	Body,
	Card,
	FullWidth,
	NavigationItem,
	SectionGrid,
	TopGrid,
};

export const components = {
	article: Article,
	body: Body,
	card: Card,
	full_width: FullWidth,
	navigation_item: NavigationItem,
	section_grid: SectionGrid,
	top_grid: TopGrid,
};
